In [2]:
import numpy as np
arr = np.array([23,6,34,45,6])
arr_fillter = np.where(arr == 6)
print(arr_fillter)

(array([1, 4]),)


In [3]:
print(arr)

[23  6 34 45  6]


In [8]:
a = arr_fillter = arr%2 == 0
print(arr_fillter)
print(arr[arr_fillter]) 

[False  True  True False  True]
[ 6 34  6]


In [20]:
c = np.array([5], ndmin=4)      # we can give the dimantation of array
print(np.ndim(c))                  # we can check dimantation of array

4


In [23]:
a = np.array([3,5,6,78,89,8,3,0,5])
print(np.sort(a))
print(type(a))

[ 0  2  3  3  5  5  6  8 78 89]
<class 'numpy.ndarray'>


In [34]:
a = np.array([2,34, 45, 56,7,2,2, 9])
x = [True, False, True, True, False, True, False, False]
newarr = a[x]
print(newarr)



[ 2 45 56  2]


In [36]:
a = np.array([2, 3,4,5,6,2,2,7,8,9])
b = np.where(a == 2)
print(b)

(array([0, 5, 6]),)


In [48]:
a = np.array([3,4,6,7,8,9,0])
b = np.where(a %2 == 0)
print(b)
c = np.where(a %2 != 0)
print(c)

(array([1, 2, 4, 6]),)
(array([0, 3, 5]),)


In [51]:
arr1 = np.array([2,4,3,5,6,])
arr2 = np.array([22,33,44,55])
arr3 = np.concatenate((arr1, arr2))
print(arr3)

[ 2  4  3  5  6 22 33 44 55]
